# Generated by Django 3.1.1 on 2020-11-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0002_auto_20201031_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khuyenmai',
            name='ngaybd',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='khuyenmai',
            name='ngaykt',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='khuyenmai',
            name='ngaytao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
