# Generated by Django 3.1.1 on 2020-11-10 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0003_auto_20201106_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='km',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sanpham.khuyenmai'),
        ),
    ]
