# Generated by Django 3.1.1 on 2020-11-01 03:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taikhoan', '0001_initial'),
        ('sanpham', '0002_auto_20201031_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='NguonNhap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Please enter right phone number', regex='^0\\d{9,11}')])),
            ],
        ),
        migrations.CreateModel(
            name='PhieuNhap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tongtien', models.IntegerField()),
                ('ngaytao', models.DateTimeField(auto_now_add=True)),
                ('nguonnhap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhaphang.nguonnhap')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taikhoan.taikhoan')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietPhieuNhap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soluong', models.IntegerField()),
                ('phieunhap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhaphang.phieunhap')),
                ('sanpham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.sanpham')),
            ],
        ),
    ]
