# Generated by Django 3.1.1 on 2020-11-14 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0004_auto_20201110_2348'),
        ('nhaphang', '0003_remove_phieunhap_tongtien'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chitietphieunhap',
            unique_together={('sanpham', 'phieunhap')},
        ),
    ]
