# Generated by Django 3.1.1 on 2020-10-31 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChiTietDonHang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soluong', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tongtien', models.FloatField()),
                ('ngaytao', models.DateTimeField()),
                ('trangthaidonhang', models.CharField(max_length=30)),
                ('hinhthucthanhtoan', models.CharField(max_length=50)),
            ],
        ),
    ]
