# Generated by Django 3.1.1 on 2020-10-31 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sanpham', '0002_auto_20201031_1331'),
        ('banhang', '0004_auto_20201031_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitietdonhang',
            name='donhang',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='banhang.donhang'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='chitietdonhang',
            unique_together={('sanpham', 'donhang')},
        ),
        migrations.RemoveField(
            model_name='chitietdonhang',
            name='donhangn',
        ),
    ]
