# Generated by Django 3.1.1 on 2020-11-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banhang', '0006_auto_20201106_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donhang',
            name='hinhthucthanhtoan',
        ),
        migrations.RemoveField(
            model_name='donhang',
            name='tongtien',
        ),
        migrations.RemoveField(
            model_name='donhang',
            name='trangthaidonhang',
        ),
        migrations.AddField(
            model_name='chitietdonhang',
            name='tongtien',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
