# Generated by Django 3.1.1 on 2020-11-07 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banhang', '0007_auto_20201107_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chitietdonhang',
            name='tongtien',
        ),
    ]
