# Generated by Django 3.1.1 on 2020-11-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banhang', '0010_auto_20201107_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitietdonhang',
            name='gia',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
