# Generated by Django 3.1.1 on 2020-11-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banhang', '0012_remove_donhang_tongtien'),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='tongtien',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
