# Generated by Django 3.1.1 on 2020-11-07 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banhang', '0013_donhang_tongtien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donhang',
            name='tongtien',
        ),
    ]
