# Generated by Django 3.1.1 on 2020-11-10 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banhang', '0014_remove_donhang_tongtien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chitietdonhang',
            name='gia',
        ),
    ]
