# Generated by Django 3.1.1 on 2020-11-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banhang', '0015_remove_chitietdonhang_gia'),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='tongtien',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
