# Generated by Django 3.1.1 on 2020-11-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banhang', '0017_remove_donhang_tongtien'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitietdonhang',
            name='gia',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
