# Generated by Django 3.1.1 on 2020-11-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banhang', '0018_chitietdonhang_gia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitietdonhang',
            name='gia',
            field=models.FloatField(),
        ),
    ]
