# Generated by Django 3.1.1 on 2020-11-10 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banhang', '0019_auto_20201110_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitietdonhang',
            name='gia',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
